# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release Chirp

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish Executables
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false
          dotnet publish -c Release -r osx-x64 --self-contained false
          dotnet publish -c Release -r linux-x64 --self-contained false
          
      - name: Create ZIP Files
        run: |
          zip -j Chirp-Win.zip SimpleDB/bin/Release/net7.0/win-x64/publish/SimpleDB.dll Chirp.CLI/bin/Release/net7.0/win-x64/publish/Chirp.CLI.dll
          zip -j Chirp-OSX.zip SimpleDB/bin/Release/net7.0/osx-x64/publish/SimpleDB.dll Chirp.CLI/bin/Release/net7.0/osx-x64/publish/Chirp.CLI.dll
          zip -j Chirp-Linux.zip SimpleDB/bin/Release/net7.0/linux-x64/publish/SimpleDB.dll Chirp.CLI/bin/Release/net7.0/linux-x64/publish/Chirp.CLI.dll

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Chirp-Win.zip
            Chirp-OSX.zip
            Chirp-Linux.zip
